### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by 1429904852** [WasifurRahman/BERT_multimodal_transformer#1]
Can you provide the readme.md?

**Comment by davidlowjw** [comment]
Hi @WasifurRahman , would you kindly provide us the steps to replicate the results reported?

**Comment by RE-N-Y** [comment]
@davidlowjw  @1429904852  Apologies for the delay in response, currently @WasifurRahman and I have been quite busy recently so we have not had a time to reply back. We are currently occupied but I will be cleaning up the code significantly within 2~3 weeks so that people will have a good README.md and guide for running the code. For the reported results, the configs are archived in our severs so I will do my best to retrieve them. Worst case, we will re-run some of the experiments to at least replicate our main results. Thank you for your patience.

**TODO:**

- [x] Clean-up / comment code and attach README.md
- [x] Recover / replicate main results from paper

**Comment by davidlowjw** [comment]
@RE-N-Y Thanks for your prompt response. Really appreciate the kind gestures to clean up the code. Looking forward to the  README 👍

**Comment by RE-N-Y** [comment]
## Current update: 

1. Clean-up is in progress at "cleanup" branch.
2. MAG-BERT modeling code will be posted and MAG-XLNET code will be posted afterwards
3. Once MAG-BERT / MAG-XLNET is set up, hyper parameter runs will be set up in Weights and Biases and will be posted here after it achieves results on-par with one reported at the paper.

**Comment by davidlowjw** [comment]
@RE-N-Y thanks for the update!

**Comment by RE-N-Y** [comment]
@davidlowjw @1429904852 Just would like to inform you that the master branch has been cleaned up and updated with a readm.md. I have tested it out with conda environment provided via requirements.txt on K80 GPU.

Let us know if anyone has issues running the code. Once I get some time, I will also try to reproduce couple of main results. I will try to dig up the server for exact configuration for our best run, worst case, I will try to re-run the hyper-parameter searches again which may take some time and GPU resources.
I will close the issue for now, but feel free to re-open it or request a PR if you have suggestions to README.md!
