### ISSUE TITLE
Image+Text

### ISSUE THREAD

**Issue by darthgera123** [WasifurRahman/BERT_multimodal_transformer#15]
Can this model work only for image+text ? Like can we make acoustic dim=0 and run this code

**Comment by RE-N-Y** [comment]
@darthgera123 The model can certainly work with image + text. Although instead of setting acoustic dimension to zero, I personally prefer setting image embedding to zero vectors. Setting dimension to zero can possibly lead to zero division error since we didn't test the code for edge cases. In fact, image/acoustic are arbitrary names assigned to modalities, so attempting to use MAG on knowledge-graph-based embedding or alternative text embedding is also possible! The only requirement is that these modalities need to be word-aligned.

**Comment by RE-N-Y** [comment]
Closing the issue due to inactivity
