### ISSUE TITLE
Two numbers of BA and F1

### ISSUE THREAD

**Issue by stdoo** [WasifurRahman/BERT_multimodal_transformer#16]
Hi, I am reading your paper recently and I am a bit confused about the two numbers of BA and F1. I have tried to find the calculation on the left side of "/", but the metric code is not provided. So, what's the difference between these two calculations? Is it possible to switch them in your code?

**Comment by RE-N-Y** [comment]
In MOSI/MOSEI datasets, there are instances where a "neutral label" (i.e. 0) is provided. In previous papers, authors have evaluated performances by including/excluding these instances. That's why we provided both metrics in the paper. The method `test_score_model` provides an option (use_zero) to select between these metrics.

**Comment by stdoo** [comment]
@RE-N-Y Thanks a lot.
